name: "Deploy to staging env"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/stage-key
          chmod 600 ~/.ssh/stage-key

          ssh-keyscan 98.84.132.41 >> ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -vvv -i ~/.ssh/stage-key ubuntu@98.84.132.41 -t "
            cd code/monorepo-deploy/
            git remote set-url origin https://github.com/Harsh8089/monorepo-deploy.git
            git checkout main
            git pull
          "
