name: "Deploy to staging env"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/stage-key
          chmod 600 ~/.ssh/stage-key

      - name: List dir
        run: |
          ssh -i ~/.ssh/stage-key ubuntu@98.84.132.41
          ls
